# Generated by Django 4.0.5 on 2022-11-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pay_day',
            field=models.IntegerField(null=True),
        ),
    ]
